# example1: with 4GB ram, 1 cpu core coretex-a57, qmp server in /tmp/qmp.sock, monitor server with telnet at port 4444, network supported, port forword host 2222 to client 22, load pvpanic-pci device, mounted shared 9p network filesystem and gdb server listened at port 1234 with no-wait for gdb connection.
qemu-system-aarch64 -cpu cortex-a57 -machine virt -nographic -net nic,model=virtio,macaddr=52:54:00:12:34:58 -net user,hostfwd=::2222-:22 -m 4G -monitor telnet::4444,server=on,wait=off -smp 1 -append "console=ttyAMA0 root=/dev/vda2 rw" -kernel /data/bupt-rtos/RROS/arch/arm64/boot/Image -drive file=/data/bupt-rtos/rros-rasp.qcow2,format=qcow2,index=0,media=disk -device pvpanic-pci -qmp unix:/tmp/qmp.sock,server=on,wait=off -action shutdown=pause,panic=none -virtfs local,path=/mnt/shared,mount_tag=host0,security_model=passthrough,id=host0 -s

# example2: like example1, but without monitor at port 4444, port hostfwd, with snapshot mode, 
qemu-system-aarch64 -cpu cortex-a57 -machine virt -nographic -net nic,model=virtio,macaddr=52:54:00:12:34:58 -net user -m 4G -smp 1 -append "console=ttyAMA0 root=/dev/vda2 rw" -kernel /data/bupt-rtos/RROS/arch/arm64/boot/Image -drive file=/data/bupt-rtos/rros-rasp.qcow2,format=qcow2,index=0,media=disk,snapshot=on -device pvpanic-pci -qmp unix:/tmp/qmp.sock,server=on,wait=off -action shutdown=pause,panic=none -virtfs local,path=/mnt/shared,mount_tag=host0,security_model=passthrough,id=host0 -s

# example3: like example2, but use unix socket instead port 1234 to debug
qemu-system-aarch64 -cpu cortex-a57 -machine virt -nographic -net nic,model=virtio,macaddr=52:54:00:12:34:58 -net user -m 4G -smp 1 -append "console=ttyAMA0 root=/dev/vda2 rw" -kernel /data/bupt-rtos/RROS/arch/arm64/boot/Image -drive file=/data/bupt-rtos/rros-rasp.qcow2,format=qcow2,index=0,media=disk,snapshot=on -device pvpanic-pci -qmp unix:/tmp/qmp.sock,server=on,wait=off -action shutdown=pause,panic=none -virtfs local,path=/mnt/shared,mount_tag=host0,security_model=passthrough,id=host0 -chardev socket,path=/tmp/gdb-server.sock,server=on,wait=off,id=gdb0 -gdb chardev:gdb0 

# example4: like example3, but use `-mon` with `-chardev` to start `qmp` server, it will create a new unix socket when it doesn't exist
qemu-system-aarch64 -cpu cortex-a57 -machine virt -nographic -net nic,model=virtio,macaddr=52:54:00:12:34:58 -net user -m 4G -smp 1 -append "console=ttyAMA0 root=/dev/vda2 rw" -kernel /data/bupt-rtos/RROS/arch/arm64/boot/Image -drive file=/data/bupt-rtos/rros-rasp.qcow2,format=qcow2,index=0,media=disk,snapshot=on -device pvpanic-pci -action shutdown=pause,panic=none -virtfs local,path=/mnt/shared,mount_tag=host0,security_model=passthrough,id=host0 -chardev socket,path=/tmp/gdb-server.sock,server=on,wait=off,id=gdb0 -gdb chardev:gdb0 -chardev socket,path=/tmp/qmp.sock,server=on,wait=off,id=qmp -mon chardev=qmp,mode=control,pretty=on

# example5: like example4, but use `netdev` and `device` to configure the virtual net adapter
qemu-system-aarch64 -cpu cortex-a57 -machine virt -nographic -net nic,model=virtio,macaddr=52:54:00:12:34:58 -netdev user,hostfwd=tcp::2222-:22,id=eth0 -device virtio-net-device,netdev=eth0 -m 4G -smp 1 -append "console=ttyAMA0 root=/dev/vda1 rw" -kernel /root/lava-qemu-flip/pvpanic_Image -drive file=/root/lava-qemu-flip/ubuntu-mini.qcow2,format=qcow2,index=0,media=disk,snapshot=on -device pvpanic-pci -action shutdown=pause,panic=none -chardev socket,path=/tmp/gdb-server.sock,server=on,wait=off,id=gdb0 -gdb chardev:gdb0 -chardev socket,path=/tmp/qmp.sock,server=on,wait=off,id=qmp -mon chardev=qmp,mode=control,pretty=on

# example6: like example5, use backend mem file in addition
qemu-system-aarch64 -cpu cortex-a57 -object memory-backend-file,id=pc.ram,size=512M,mem-path=/tmp/backend-mem,prealloc=on,share=on -m 512M -machine virt,memory-backend=pc.ram -nographic -net nic,model=virtio,macaddr=52:54:00:12:34:58 -netdev user,hostfwd=tcp::2222-:22,id=eth0 -device virtio-net-device,netdev=eth0  -smp 1 -append "console=ttyAMA0 root=/dev/vda1 rw" -kernel /root/lava-qemu-flip/pvpanic_Image -drive file=/root/lava-qemu-flip/ubuntu-mini.qcow2,format=qcow2,index=0,media=disk,snapshot=on -device pvpanic-pci -action shutdown=pause,panic=none -chardev socket,path=/tmp/gdb-server.sock,server=on,wait=off,id=gdb0 -gdb chardev:gdb0 -chardev socket,path=/tmp/qmp.sock,server=on,wait=off,id=qmp -mon chardev=qmp,mode=control,pretty=on

# example7: like example6, use kvm accelerator in addition
qemu-system-aarch64 -enable-kvm -cpu host -object memory-backend-file,id=pc.ram,size=512M,mem-path=/tmp/backend-mem,prealloc=on,share=on -m 512M -machine virt,memory-backend=pc.ram,accel=kvm -nographic -net nic,model=virtio,macaddr=52:54:00:12:34:58 -netdev user,hostfwd=tcp::2222-:22,id=eth0 -device virtio-net-device,netdev=eth0  -smp 1 -append "console=ttyAMA0 root=/dev/vda1 rw" -kernel /root/lava-qemu-flip/pvpanic_Image -drive file=/root/lava-qemu-flip/ubuntu-mini.qcow2,format=qcow2,index=0,media=disk,snapshot=on -device pvpanic-pci -action shutdown=pause,panic=none -chardev socket,path=/tmp/gdb-server.sock,server=on,wait=off,id=gdb0 -gdb chardev:gdb0 -chardev socket,path=/tmp/qmp.sock,server=on,wait=off,id=qmp -mon chardev=qmp,mode=control,pretty=on

qemu-system-aarch64 -cpu cortex-a57 -m 512M -machine virt -nographic -net nic,model=virtio,macaddr=52:54:00:12:34:58 -netdev user,hostfwd=tcp::2222-:22,id=eth0 -device virtio-net-device,netdev=eth0  -smp 1 -append "console=ttyAMA0 root=/dev/vda1 rw" -kernel /root/lava-qemu-flip/openeuler_image -drive file=/root/lava-qemu-flip/ubuntu-mini.qcow2,format=qcow2,index=0,media=disk -device pvpanic-pci -action shutdown=pause,panic=none -chardev socket,path=/tmp/gdb-server.sock,server=on,wait=off,id=gdb0 -gdb chardev:gdb0 -chardev socket,path=/tmp/qmp.sock,server=on,wait=off,id=qmp -mon chardev=qmp,mode=control,pretty=on
